#!/usr/bin/env bash
set -u
dir="$1" stream="$2"; shift 2
mkdir "$dir/$stream.lock"
chmod 700 "$dir/$stream.lock"
jq -cn --argjson pid "$$" '{pid:$pid,start_time:"definitely not this process",nonce:"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"}' \
  >"$dir/$stream.lock/owner.json"
chmod 600 "$dir/$stream.lock/owner.json"
exec "$@"
